security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Users
                property: username

    encoders:
        App\Entity\Users:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /